# Generated by Django 2.0.2 on 2018-03-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtaghighjack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='tag',
            field=models.CharField(default='', max_length=15),
        ),
    ]
